import json
import os


def generate_readme(directory: str = ".") -> None:
    """
    Scans the given directory for .meta.json sidecar files and generates a README.md.
    """
    readme_path = os.path.join(directory, "README.md")
    
    # Static header for the README
    content = [
        "# Corpus: AI and the Labor Market",
        "",
        "> **Note:** This file is auto-generated by `generate_readme.py` from the `.meta.json` sidecar metadata files. Do not edit it manually.",
        "",
        "This directory contains the test documents for the RAG system and their corresponding machine-readable metadata.",
        "",
        "> **Policy:** The documents in this directory are checked into version control to enable fast, reproducible testing without external dependencies. "
        "This is only appropriate as long as all documents are (a) publicly and openly licensed (Open Access / Creative Commons), "
        "(b) reasonably small in size, and (c) limited in number. "
        "If you need to work with proprietary, restricted, or large documents, create a `.env` file based on `.env.example` "
        "and set `CORPUS_PATH` to a local directory outside this repository instead of adding such files here.",
        "",
        "## Metadata Structure",
        "Each document is accompanied by a sidecar JSON file named `<original-filename>.meta.json` (e.g., `document.pdf.meta.json`). "
        "This convention works for any document type. "
        "These JSON files contain all legally required attribution data (author, publication date, source, license). "
        "They are designed to be ingested directly into the vector database to ensure accurate source citations by the RAG chatbot.",
        "",
        "## Document Overview",
        "All documents are included in their original, unmodified form under their respective Open Access or Creative Commons licenses.",
        ""
    ]

    # Find all .meta.json sidecar files, sort them alphabetically
    files = sorted([f for f in os.listdir(directory) if f.endswith(".meta.json")])

    if not files:
        content.append("*No metadata files found in this directory.*")
    
    # Parse each JSON file and append its data to the README content
    for filename in files:
        filepath = os.path.join(directory, filename)
        source_filename = filename.removesuffix(".meta.json")
        
        with open(filepath, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                
                # Extract values with fallbacks
                title = data.get("title", "Unknown Title")
                author = data.get("author", "Unknown Author")
                publication_date = data.get("publication_date", "")
                license_type = data.get("license", "Unknown License")
                source_url = data.get("source_url", "")
                
                content.append(f"### {title}")
                content.append(f"- **File:** `{source_filename}`")
                content.append(f"- **Author:** {author}")
                if publication_date:
                    content.append(f"- **Published:** {publication_date}")
                content.append(f"- **License:** {license_type}")
                if source_url:
                    content.append(f"- **Source:** [Link]({source_url})")
                content.append("") # Add a blank line for spacing
                
            except json.JSONDecodeError:
                print(f"Warning: Could not read valid JSON from {filename}")

    # Write the assembled content to README.md
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
        
    print(f"Successfully generated {readme_path} containing {len(files)} documents.")

if __name__ == "__main__":
    generate_readme()